@startuml
class com.gm.ultifi.service.cabinclimate.utils.TaskRunner {
- {static} String TAG
- {static} int CORE_THREADS
- {static} long KEEP_ALIVE_SECONDS
- {static} TaskRunner sTaskRunner
- ThreadPoolExecutor mExecutor
- Handler mHandler
+ {static} TaskRunner getInstance()
- ThreadPoolExecutor newThreadPoolExecutor()
+ void execute(Runnable)
+ void executeCallable(Callable<R>,OnCompletedCallback<R>)
+ ExecutorService getExecutor()
+ void shutdownService()
}
interface com.gm.ultifi.service.cabinclimate.utils.TaskRunner$OnCompletedCallback {
~ void onComplete(R)
}
class com.gm.ultifi.service.cabinclimate.utils.cache.LruMap {
- int mCapacity
# boolean removeEldestEntry(Map.Entry<K,V>)
}
class com.gm.ultifi.service.cabinclimate.response.config.PropertyConfig {
- boolean mIsReadOnly
- String mProtobufField
- float mRate
- String mResName
- Class<?> mType
- String mSignalName
+ Class<?> getClassType()
+ boolean getIsReadOnly()
+ String getProtobufField()
+ float getRate()
+ String getResName()
+ String getSignalName()
+ String toString()
}
class com.gm.ultifi.service.cabinclimate.response.config.PropertyConfig$Builder {
- boolean isReadOnly
- String resName
- String protobufField
- float rate
- String signalName
- Class<?> type
+ PropertyConfig build()
+ Builder setClassType(Class<?>)
+ Builder setProtobufField(String)
+ Builder setRate(float)
+ Builder setReadOnly(boolean)
+ Builder setResName(String)
+ Builder setSignalName(String)
}
interface com.gm.ultifi.service.cabinclimate.response.mapper.BaseMapper {
~ String BASE_URI_SERVICE
~ String VERSION
~ UEntity SERVICE
~ String CLIMATE_ZONE
~ String CLIMATE_ZONE_URI
~ String SYSTEM_SETTINGS
~ String SYSTEM_SETTINGS_URI
~ Cache cache
~ {static} BaseMapper getMapper(int)
~ {static} BaseMapper getMapper(String)
~ boolean isRepeatedSignal()
~ Map<String,Any> generateProtobufMessage(CarPropertyExtensionManager,Object,PropertyConfig)
~ PropertyConfig getConfig(int)
~ PropertyConfig getConfig(String)
~ void setAreaId(Integer)
~ void setPropertyStatus(int)
}
class com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager {
- {static} String TAG
- CarPropertyManager mPropertyManager
- Object mLock
- ArraySet<CarPropertyExtensionCallback> mExtCallbacks
- CarPropertyManager.CarPropertyEventCallback mPropertyCallback
+ void registerCallback(CarPropertyExtensionCallback)
+ void unregisterCallback(CarPropertyExtensionCallback)
+ String setProperty(Class,int,int,Object)
+ Boolean isPropertyAvailable(int,int)
+ Boolean getBooleanProperty(int,int)
- Boolean getPropertyValue(int,int)
+ Integer getIntegerProperty(int,int)
- void handleOnChangeEvent(CarPropertyValue)
- void handleOnErrorEvent(int,int)
}
class com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl {
- WeakReference<CarPropertyExtensionManager> mManager
+ void onChangeEvent(CarPropertyValue)
+ void onErrorEvent(int,int)
}
interface com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager$CarPropertyExtensionCallback {
~ void onChangeEvent(CarPropertyValue<?>)
~ void onErrorEvent(int,int)
}
enum com.gm.ultifi.service.access.response.config.enums.SunroofEnum {
+  SUNROOF_PERCENTAGE_POSITION_STATUS
- PropertyConfig mConfig
- Integer mPropertyId
- String mSignalName
- {static} Map<Integer,SunroofEnum> PROPERTY_ID_MAP
+ Integer getPropertyId()
+ String getResName()
+ String getSignal()
+ float getRate()
+ {static} Map<Integer,SunroofEnum> getPropertyIdMap()
+ PropertyConfig getPropertyConfig()
}
class android.os.SystemProperties {
+ {static} boolean getBoolean(String,boolean)
}
class com.gm.ultifi.service.cabinclimate.manager.request.helper.ZoneRequestProcessor {
- {static} String TAG
+ Status processRequest()
}
interface com.gm.ultifi.service.access.utils.cache.Cache {
~ void clear()
~ V get(K)
~ int getMaxMemorySize()
~ int getMemorySize()
~ V put(K,V)
~ V remove(K)
}
interface com.gm.ultifi.service.cabinclimate.manager.ConnectionManager {
~ void connect()
~ void init()
~ void stop()
}
class com.gm.ultifi.service.cabinclimate.utils.ResourceMappingConstants {
+ {static} String SYSTEM_SETTINGS
}
class com.gm.ultifi.service.MainActivity {
# void onCreate(Bundle)
}
class com.gm.ultifi.service.cabinclimate.response.config.CarPropertyDataModel {
- int mAreaId
- Class<?> mClassType
- String mFieldName
- boolean mIsValid
- int mPropertyId
- Object mValue
+ int getAreaId()
+ Class<?> getClassType()
+ String getFieldName()
+ int getPropertyId()
+ Object getValue()
+ boolean isValid()
+ void setAreaId(int)
}
class com.gm.ultifi.service.access.manager.request.helper.SunroofRequestProcessor {
- {static} String TAG
+ Status processRequest()
# Boolean checkPositionPreCondition(Integer)
}
class com.gm.ultifi.service.access.utils.cache.LruMap {
- int mCapacity
# boolean removeEldestEntry(Entry<K,V>)
}
class com.gm.ultifi.service.access.manager.UltifiLinkMonitor {
- {static} String TAG
- Context mContext
- UltifiLink mUltifiLink
- UltifiLink.ServiceLifecycleListener mUltifiLinkLifeCycleListener
- UltifiLink.RequestListener mRPCRequestListener
- UltifiLink.RequestEventListener mRPCRequestEventListener
+ void connect()
+ void init()
+ void stop()
+ void setConnectionListener(UltifiLink.ServiceLifecycleListener)
+ void setRPCRequestListener(UltifiLink.RequestListener)
+ void setRPCRequestListener(UltifiLink.RequestEventListener)
+ void registerRPCMethod(String[])
+ boolean isUltifiLinkReady()
+ void publish(CloudEvent)
}
class com.gm.ultifi.service.access.utils.ResourceMappingConstants {
+ {static} String SUNROOF_FRONT
}
class com.gm.ultifi.service.AccessService {
- {static} String TAG
- {static} String SDV_ENABLE_PROP
- {static} String CHANNEL_ID
- {static} String CHANNEL_NAME
+ {static} AccessService context
- boolean isSDVEnabled
- ServiceLaunchManager mLaunchManager
+ void onCreate()
+ IBinder onBind(Intent)
+ void onDestroy()
- void init()
- void startForeground()
}
class com.gm.ultifi.service.access.manager.CanManagerMonitor {
- {static} String TAG
- {static} int MIN_UPDATE_TIME
- Context mContext
- CanManager mCanManager
- CanManager.CANBridgeListener mCANBridgeListener
- OnCanManagerConnectionListener mCanManagerConnListener
+ void connect()
+ void init()
+ void stop()
+ CanManager getCanManager()
+ boolean isCanManagerReady()
+ void setConnectionListener(OnCanManagerConnectionListener)
+ void setCANBridgeListener(CanManager.CANBridgeListener)
+ void registerSignal(String[])
+ void unRegisterSignal(String[])
+ void sendSignalsToCanManager(Signal[])
}
interface com.gm.ultifi.service.access.manager.CanManagerMonitor$OnCanManagerConnectionListener {
~ void onCanManagerConnectionChanged(boolean)
}
class com.gm.ultifi.service.cabinclimate.utils.Utility {
- {static} String TAG
+ {static} List<String> buildTopicsList()
+ {static} boolean convertToBoolean(String)
+ {static} Boolean getBooleanValue(Signal)
+ {static} byte[] getBytes(Signal)
+ {static} Float getFloatValue(Signal)
+ {static} Integer getIntValue(Signal)
+ {static} K getKey(Map<K,V>,V)
+ {static} T getSignalValues(Signal)
+ {static} boolean between(int,int,int)
+ {static} boolean isInRange(double,double,double)
+ {static} boolean isInRange(float,float,float)
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager {
- {static} String TAG
- CarPropertyManager mPropertyManager
- Object mLock
- ArraySet<CarPropertyExtensionCallback> mExtCallbacks
- CarPropertyManager.CarPropertyEventCallback mPropertyCallback
+ void registerCallback(CarPropertyExtensionCallback)
+ void unregisterCallback(CarPropertyExtensionCallback)
+ String setProperty(Class,int,int,Object)
+ Boolean getBooleanProperty(int,int)
- Boolean getPropertyValue(int,int)
- void handleOnChangeEvent(CarPropertyValue)
- void handleOnErrorEvent(int,int)
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl {
- WeakReference<CarPropertyExtensionManager> mManager
+ void onChangeEvent(CarPropertyValue)
+ void onErrorEvent(int,int)
}
interface com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager$CarPropertyExtensionCallback {
~ void onChangeEvent(CarPropertyValue<?>)
~ void onErrorEvent(int,int)
}
class com.gm.ultifi.service.access.manager.propertymanager.ProtobufMessageIds {
+ {static} String POSITION
}
class com.gm.ultifi.service.access.manager.propertymanager.ProtobufMessageIds$SunroofFieldMask {
+ {static} String SUNROOF
+ {static} String POWER_ON_FIELD_MASK
}
class com.gm.ultifi.service.cabinclimate.manager.ServiceLaunchManager {
- {static} String TAG
- {static} String ZONE_AREA_MAPPING_FILE
- CanManagerMonitor mCanMgrMonitor
- CanManagerMonitor.OnCanManagerConnectionListener mOnCanManagerConnectionListener
- CanManager.CANBridgeListener mCanSignalListener
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
- CarPropertyManagerMonitor.OnCarManagerConnectionListener mOnCarPropertyMgrConnListener
- CarPropertyExtensionManager.CarPropertyExtensionCallback mPropertyExtMgrCallback
- UltifiLinkMonitor mUltifiLinkMonitor
- UltifiLink.ServiceLifecycleListener mOnUltifiLinkLifeCycleListener
- UltifiLinkRequestListener mUltifiLinkRequestListener
- USubscription.BlockingStub mUSubscription
- boolean isCanSignalsRegistered
- boolean isCarPropertiesRegistered
- boolean isUltifiLinkConnected
- void onUltifiLinkConnected(UltifiLink)
- void onUltifiLinkDisconnected()
+ void init()
+ void stop()
+ List<CloudEvent> buildCarPropertyCloudEvents(CarPropertyValue<?>)
+ List<CloudEvent> buildSignalCloudEvents(Signal)
- void createTopic(String)
- void registerCabinClimateSignals()
- void unRegisterCabinClimateSignals()
- void registerCanSignals(List<String>)
- void unRegisterCanSignals(List<String>)
- void registerCarPropertyCallback()
- void unRegisterCarPropertyCallback()
}
class com.gm.ultifi.service.access.response.config.CarPropertyDataModel {
- int mAreaId
- Class<?> mClassType
- String mFieldName
- boolean mIsValid
- int mPropertyId
- Object mValue
+ int getAreaId()
+ Class<?> getClassType()
+ String getFieldName()
+ int getPropertyId()
+ Object getValue()
+ boolean isValid()
+ void setAreaId(int)
}
class com.gm.ultifi.service.cabinclimate.manager.request.helper.SystemSettingsRequestProcessor {
- {static} String TAG
+ Status processRequest()
}
class com.gm.ultifi.service.access.utils.VehicleDataConstants {
+ {static} String EMPTY_ZONE_MESSAGE
+ {static} int FACE
+ {static} int FLOOR
+ {static} int DEFROST
+ {static} int FAHRENHEIT
+ {static} int CELSIUS
+ {static} String INVALID_PATH_MESSAGE
+ {static} String INVALID_REQUEST_MESSAGE
+ {static} int RECIRC
+ {static} String SYSTEM_SETTINGS_SUCCESS_MESSAGE
+ {static} String UNSUPPORTED_ZONE
+ {static} String ZONE_SUCCESS_MESSAGE
}
class com.gm.ultifi.service.cabinclimate.utils.SignalMappingConstants {
}
class com.gm.ultifi.service.cabinclimate.utils.SignalMappingConstants$SystemSettings {
+ {static} String ESTIMATED_CABIN_TEMPERATURE
+ {static} String FAILURE_INDICATION
+ {static} String SAFETY_TEMPERATURE_INDICATION
}
class com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory {
- {static} String TAG
+ {static} RequestProcessorFactory getInstance()
+ RequestProcessor getRequestProcessor(String)
}
class com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory$RequestProcessorFactorySingleton {
- {static} RequestProcessorFactory INSTANCE
}
interface com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory$RequestProcessor {
~ Status processRequest()
~ void setCarPropertyManagerMonitor(CarPropertyManagerMonitor)
~ void setRequestMessage(Request)
}
class com.gm.ultifi.service.access.manager.request.listeners.UltifiLinkRequestEventListener {
- {static} String TAG
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
+ void onEvent(CloudEvent,CompletableFuture<Any>)
}
abstract class com.gm.ultifi.service.access.manager.request.helper.BaseRequestProcessor {
- CarPropertyManagerMonitor mCarPropertyManager
# Request mRequest
+ CarPropertyExtensionManager getCarPropertyExtensionManager()
+ boolean isCarPropertyExtensionManagerNull()
+ void setCarPropertyManagerMonitor(CarPropertyManagerMonitor)
+ void setRequestMessage(Request)
# String setCarProperty(Class<?>,int,int,Object)
}
interface com.gm.ultifi.service.access.response.config.enums.SignalInfo {
~ String getResName()
~ String getSignal()
}
class com.gm.ultifi.service.access.response.config.PropertyConfig {
- boolean mIsReadOnly
- String mProtobufField
- float mRate
- String mResName
- Class<?> mType
- String mSignalName
+ Class<?> getClassType()
+ boolean getIsReadOnly()
+ String getProtobufField()
+ float getRate()
+ String getResName()
+ String getSignalName()
+ String toString()
}
class com.gm.ultifi.service.access.response.config.PropertyConfig$Builder {
- boolean isReadOnly
- String resName
- String protobufField
- float rate
- String signalName
- Class<?> type
+ PropertyConfig build()
+ Builder setClassType(Class<?>)
+ Builder setProtobufField(String)
+ Builder setRate(float)
+ Builder setReadOnly(boolean)
+ Builder setResName(String)
+ Builder setSignalName(String)
}
class com.gm.ultifi.service.access.utils.SignalMappingConstants {
}
class com.gm.ultifi.service.access.utils.SignalMappingConstants$SystemSettings {
+ {static} String ESTIMATED_CABIN_TEMPERATURE
+ {static} String FAILURE_INDICATION
+ {static} String SAFETY_TEMPERATURE_INDICATION
}
class com.gm.ultifi.service.access.response.mapper.SunroofSomeIpMapper {
}
class com.gm.ultifi.service.access.manager.CarPropertyManagerMonitor {
- {static} String TAG
- Context mContext
- Car mCar
- Car.CarServiceLifecycleListener mCarServiceLifecycleListener
- CarPropertyManager mCarPropertyManager
- OnCarManagerConnectionListener mOnCarManagerConnectionListener
- CarPropertyExtensionManager mPropertyExtensionManager
+ void connect()
+ void init()
+ void stop()
+ boolean isCarPropertyManagerReady()
+ CarPropertyExtensionManager getCarPropertyExtensionManager()
+ void setConnectionListener(OnCarManagerConnectionListener)
+ void registerCallback(CarPropertyExtensionManager.CarPropertyExtensionCallback)
+ void unRegisterCallback(CarPropertyExtensionManager.CarPropertyExtensionCallback)
- void onCarServiceConnected()
- void onCarServiceDisconnected()
- void startCarService()
}
interface com.gm.ultifi.service.access.manager.CarPropertyManagerMonitor$OnCarManagerConnectionListener {
~ void onCarManagerConnectionChanged(boolean)
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.AreaPropertyMapper {
- {static} String TAG
- {static} JSONObject areaIDJson
- {static} HashMap<String,Integer> mAreaIdPropertyMap
- {static} HashMap<Integer,String> mAreaPropertyMap
- {static} HashMap<String,Integer[]> mZonePropertyMap
+ {static} Set<String> getZonePropertyKeys()
+ {static} Integer getZoneByZoneName(String,String)
+ {static} JSONArray getZoneNamesByAreaID(Integer,String)
}
class com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory {
- {static} String TAG
+ {static} RequestProcessorFactory getInstance()
+ RequestProcessor getRequestProcessor(String)
}
class com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory$RequestProcessorFactorySingleton {
- {static} RequestProcessorFactory INSTANCE
}
interface com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory$RequestProcessor {
~ Status processRequest()
~ void setCarPropertyManagerMonitor(CarPropertyManagerMonitor)
~ void setRequestMessage(Request)
}
interface com.gm.ultifi.service.cabinclimate.utils.cache.Cache {
~ void clear()
~ V get(K)
~ int getMaxMemorySize()
~ int getMemorySize()
~ V put(K,V)
~ V remove(K)
}
class com.gm.ultifi.service.cabinclimate.utils.VehicleDataConstants {
+ {static} String EMPTY_ZONE_MESSAGE
+ {static} int FACE
+ {static} int FLOOR
+ {static} int DEFROST
+ {static} int FAHRENHEIT
+ {static} int CELSIUS
+ {static} String INVALID_PATH_MESSAGE
+ {static} String INVALID_REQUEST_MESSAGE
+ {static} int RECIRC
+ {static} String SYSTEM_SETTINGS_SUCCESS_MESSAGE
+ {static} String UNSUPPORTED_ZONE
+ {static} String ZONE_SUCCESS_MESSAGE
}
enum com.gm.ultifi.service.cabinclimate.enums.ZoneEnum {
+  HVAC_POWER_ON
- PropertyConfig mConfig
- Integer mPropertyId
- String mSignalName
+ Integer getPropertyId()
+ String getResName()
+ String getSignal()
+ float getRate()
}
class com.gm.ultifi.service.access.manager.request.helper.SomeIpRequestProcessor {
- {static} String TAG
+ Status processRequest()
}
class com.gm.ultifi.service.cabinclimate.manager.UltifiLinkMonitor {
- {static} String TAG
- Context mContext
- UltifiLink mUltifiLink
- UltifiLink.ServiceLifecycleListener mUltifiLinkLifeCycleListener
- UltifiLink.RequestListener mRPCRequestListener
- UltifiLink.RequestEventListener mRPCRequestEventListener
+ void connect()
+ void init()
+ void stop()
+ void setConnectionListener(UltifiLink.ServiceLifecycleListener)
+ void setRPCRequestListener(UltifiLink.RequestListener)
+ void setRPCRequestListener(UltifiLink.RequestEventListener)
+ void registerRPCMethod(String[])
+ boolean isUltifiLinkReady()
+ void publish(CloudEvent)
}
class com.gm.ultifi.service.access.utils.cache.LruCache {
- {static} int DEFAULT_CAPACITY
- {static} int REMOVE_ALL
- Map<K,V> mMap
- int mMaxMemorySize
- int mMemorySize
+ {static} LruCache getInstance()
- void trimToSize(int)
+ void clear()
+ V get(K)
+ int getMaxMemorySize()
+ int getMemorySize()
+ V put(K,V)
+ V remove(K)
# int getValueSize(V)
# String getClassName()
}
class com.gm.ultifi.service.access.utils.cache.LruCache$LruCacheSingleton {
- {static} LruCache INSTANCE
}
class com.gm.ultifi.service.cabinclimate.utils.cache.LruCache {
- {static} int DEFAULT_CAPACITY
- {static} int REMOVE_ALL
- Map<K,V> mMap
- int mMaxMemorySize
- int mMemorySize
+ {static} LruCache getInstance()
- void trimToSize(int)
+ void clear()
+ V get(K)
+ int getMaxMemorySize()
+ int getMemorySize()
+ V put(K,V)
+ V remove(K)
# int getValueSize(V)
# String getClassName()
}
class com.gm.ultifi.service.cabinclimate.utils.cache.LruCache$LruCacheSingleton {
- {static} LruCache INSTANCE
}
class com.gm.ultifi.service.CabinClimateService {
- {static} String TAG
- {static} String SDV_ENABLE_PROP
- {static} String CHANNEL_ID
- {static} String CHANNEL_NAME
- boolean isSDVEnabled
- ServiceLaunchManager mLaunchManager
+ void onCreate()
+ IBinder onBind(Intent)
+ void onDestroy()
- void init()
- void startForeground()
}
interface com.gm.ultifi.service.access.manager.ConnectionManager {
~ void connect()
~ void init()
~ void stop()
}
interface com.gm.ultifi.service.access.response.mapper.BaseMapper {
~ String BASE_URI_SERVICE
~ String VERSION
~ UEntity SERVICE
~ String SUNROOF_RESOURCE
~ String SUNROOF_RESOURCE_URI
~ Cache cache
~ {static} BaseMapper getMapper(int)
~ {static} BaseMapper getMapper(String)
~ {static} BaseMapper getMapper(long)
~ boolean isRepeatedSignal()
~ Map<String,Any> generateProtobufMessage(CarPropertyExtensionManager,Object,PropertyConfig)
~ PropertyConfig getConfig(int)
~ PropertyConfig getConfig(String)
~ PropertyConfig getConfig(long)
~ void setAreaId(Integer)
~ void setPropertyStatus(int)
}
class com.gm.ultifi.service.access.manager.request.listeners.UltifiLinkRequestListener {
- {static} String TAG
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
+ void onRequest(Request,CompletableFuture<Any>)
}
class com.gm.ultifi.service.cabinclimate.response.mapper.Zone {
- {static} String TAG
- {static} int MAX_TEMP_SET_POINT
- {static} int MIN_VALUE_ZERO
- {static} List<Integer> mPropertyList
- boolean isRepeatedSignal
- int mAreaID
- int mStatus
- Map<String,com.ultifi.vehicle.body.cabin_climate.v1.Zone.Builder> zoneBuilderMap
+ {static} Zone getInstance()
+ {static} List<Integer> getPropertyList()
+ boolean isRepeatedSignal()
+ Map<String,Any> generateProtobufMessage(CarPropertyExtensionManager,Object,PropertyConfig)
+ PropertyConfig getConfig(int)
+ void setAreaId(Integer)
+ void setPropertyStatus(int)
+ String getUri(String)
}
abstract class com.gm.ultifi.service.cabinclimate.manager.request.helper.BaseRequestProcessor {
- CarPropertyManagerMonitor mCarPropertyManager
# Request mRequest
+ CarPropertyExtensionManager getCarPropertyExtensionManager()
+ boolean isCarPropertyExtensionManagerNull()
+ void setCarPropertyManagerMonitor(CarPropertyManagerMonitor)
+ void setRequestMessage(Request)
# String setCarProperty(Class<?>,int,int,Object)
# Status checkPreCondition(String,String)
}
class com.gm.ultifi.service.access.response.mapper.SunroofMapper {
- {static} String TAG
- {static} List<Integer> mPropertyList
- boolean isRepeatedSignal
- int mAreaID
- int mStatus
- Map<String,Sunroof> sunroofBuilderMap
+ {static} SunroofMapper getInstance()
+ {static} List<Integer> getPropertyList()
+ boolean isRepeatedSignal()
+ Map<String,Any> generateProtobufMessage(CarPropertyExtensionManager,Object,PropertyConfig)
+ PropertyConfig getConfig(int)
+ String getTopicUri(String)
+ void setAreaId(Integer)
+ void setPropertyStatus(int)
+ boolean checkSunroofInfo(CarPropertyExtensionManager)
}
enum com.gm.ultifi.service.cabinclimate.enums.SystemSettingsEnum {
+  HVAC_POWER_ON
- PropertyConfig mConfig
- Integer mPropertyId
- String mSignalName
+ Integer getPropertyId()
+ String getResName()
+ String getSignal()
+ float getRate()
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds {
+ {static} String POWER_ON
+ {static} String SYNC_ALL
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds$ZoneFieldMask {
+ {static} String ZONE
+ {static} String POWER_ON_FIELD_MASK
}
class com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds$SettingsFieldMask {
+ {static} String SYSTEM_SETTINGS
+ {static} String SYNC_ALL_FIELD_MASK
}
class com.gm.ultifi.service.access.manager.ServiceLaunchManager {
- {static} String TAG
- CanManagerMonitor mCanMgrMonitor
- CanManagerMonitor.OnCanManagerConnectionListener mOnCanManagerConnectionListener
- CanManager.CANBridgeListener mCanSignalListener
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
- CarPropertyManagerMonitor.OnCarManagerConnectionListener mOnCarPropertyMgrConnListener
- CarPropertyExtensionManager.CarPropertyExtensionCallback mPropertyExtMgrCallback
- UltifiLinkMonitor mUltifiLinkMonitor
- UltifiLink.ServiceLifecycleListener mOnUltifiLinkLifeCycleListener
- UltifiLinkRequestListener mUltifiLinkRequestListener
- USubscription.BlockingStub mUSubscription
- boolean isCanSignalsRegistered
- boolean isCarPropertiesRegistered
- boolean isUltifiLinkConnected
- void onUltifiLinkConnected(UltifiLink)
- void onUltifiLinkDisconnected()
+ void init()
+ void stop()
+ List<CloudEvent> buildCarPropertyCloudEvents(CarPropertyValue<?>)
+ List<CloudEvent> buildSignalCloudEvents(Signal)
+ List<CloudEvent> buildSomeIpCloudEvents(SomeIpData)
- void createTopic(String)
- void registerAccessSignals()
- void unRegisterAccessSignals()
- void registerCanSignals(List<String>)
- void unRegisterCanSignals(List<String>)
- void registerCarPropertyCallback()
- void unRegisterCarPropertyCallback()
}
class com.gm.ultifi.service.BootCompleteReceiver {
- {static} String TAG
+ void onReceive(Context,Intent)
}
interface com.gm.ultifi.service.cabinclimate.enums.SignalInfo {
~ String getResName()
~ String getSignal()
}
class com.gm.ultifi.service.cabinclimate.manager.CarPropertyManagerMonitor {
- {static} String TAG
- Context mContext
- Car mCar
- Car.CarServiceLifecycleListener mCarServiceLifecycleListener
- CarPropertyManager mCarPropertyManager
- OnCarManagerConnectionListener mOnCarManagerConnectionListener
- CarPropertyExtensionManager mPropertyExtensionManager
+ void connect()
+ void init()
+ void stop()
+ boolean isCarPropertyManagerReady()
+ CarPropertyExtensionManager getCarPropertyExtensionManager()
+ void setConnectionListener(OnCarManagerConnectionListener)
+ void registerCallback(CarPropertyExtensionManager.CarPropertyExtensionCallback)
+ void unRegisterCallback(CarPropertyExtensionManager.CarPropertyExtensionCallback)
- void onCarServiceConnected()
- void onCarServiceDisconnected()
- void startCarService()
}
interface com.gm.ultifi.service.cabinclimate.manager.CarPropertyManagerMonitor$OnCarManagerConnectionListener {
~ void onCarManagerConnectionChanged(boolean)
}
class com.gm.ultifi.service.cabinclimate.manager.CanManagerMonitor {
- {static} String TAG
- {static} int MIN_UPDATE_TIME
- Context mContext
- CanManager mCanManager
- CanManager.CANBridgeListener mCANBridgeListener
- OnCanManagerConnectionListener mCanManagerConnListener
+ void connect()
+ void init()
+ void stop()
+ CanManager getCanManager()
+ boolean isCanManagerReady()
+ void setConnectionListener(OnCanManagerConnectionListener)
+ void setCANBridgeListener(CanManager.CANBridgeListener)
+ void registerSignal(String[])
+ void unRegisterSignal(String[])
+ void sendSignalsToCanManager(Signal[])
}
interface com.gm.ultifi.service.cabinclimate.manager.CanManagerMonitor$OnCanManagerConnectionListener {
~ void onCanManagerConnectionChanged(boolean)
}
class com.gm.ultifi.service.cabinclimate.response.mapper.SystemSettings {
- {static} String TAG
- {static} double MAX_ESTD_CBN_TEMP
- {static} int MIN_ESTD_CBN_TEMP
- {static} List<Integer> mPropertyList
# {static} List<String> mSystemSettingsSignals
- boolean isRepeatedSignal
- int mAreaID
+ {static} SystemSettings getInstance()
+ {static} List<Integer> getPropertyList()
+ {static} List<String> getSignals()
+ boolean isRepeatedSignal()
+ Map<String,Any> generateProtobufMessage(CarPropertyExtensionManager,Object,PropertyConfig)
+ PropertyConfig getConfig(int)
+ PropertyConfig getConfig(String)
+ void setAreaId(Integer)
+ String getUri()
}
class com.gm.ultifi.service.cabinclimate.manager.request.listeners.UltifiLinkRequestListener {
- {static} String TAG
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
+ void onRequest(Request,CompletableFuture<Any>)
}
class com.gm.ultifi.service.cabinclimate.manager.request.listeners.UltifiLinkRequestEventListener {
- {static} String TAG
- CarPropertyManagerMonitor mCarPropertyMgrMonitor
+ void onEvent(CloudEvent,CompletableFuture<Any>)
}
class com.gm.ultifi.utils.StreamUtils {
+ {static} List<T> filter(Collection<T>,Predicate<T>)
+ {static} List<T> filter(T[],Predicate<T>)
+ {static} List<T> reject(Collection<T>,Predicate<T>)
+ {static} Set<T> mapToSet(Collection<F>,Function<? super F,T>)
+ {static} Set<T> mapToSet(Stream<F>,Function<? super F,T>)
+ {static} List<T> mapFilterNull(Collection<F>,Function<? super F,T>)
+ {static} Set<T> mapToSetFilterNull(Collection<F>,Function<? super F,T>)
+ {static} List<T> map(Collection<F>,Function<? super F,T>)
+ {static} List<T> map(F[],Function<? super F,T>)
+ {static} List<T> map(Stream<F>,Function<? super F,T>)
+ {static} List<T> filterAndMap(Collection<F>,Predicate<F>,Function<? super F,T>)
+ {static} Map<K,V> toMap(Stream<V>,Function<V,K>)
+ {static} Map<K,V> toMap(Collection<V>,Function<V,K>)
+ {static} Map<K,V> toMap(Collection<F>,Function<F,K>,Function<F,V>)
+ {static} Map<K,V> toMap(Stream<F>,Function<F,K>,Function<F,V>)
+ {static} Map<K,List<V>> groupingBy(Collection<V>,Function<V,K>)
+ {static} Map<K,List<V>> groupingBy(Stream<V>,Function<V,K>)
+ {static} Map<K,Set<V>> groupingByAndToSet(Collection<D>,Function<D,K>,Function<D,V>)
+ {static} Map<K,List<V>> groupingByAndToList(Collection<D>,Function<D,K>,Function<D,V>)
+ {static} BigDecimal sum(Collection<S>,Function<S,BigDecimal>)
+ {static} BigDecimal sum(Collection<S>,ToIntFunction<S>)
+ {static} BigDecimal sum(Collection<S>,ToLongFunction<S>)
+ {static} List<T> flatMap(Collection<List<T>>)
+ {static} List<T> flatMap(Collection<R>,Function<R,Stream<T>>)
+ {static} T naturalOrderingMax(Stream<T>)
+ {static} T naturalOrderingMin(Stream<T>)
+ {static} long distinctCount(Stream<?>)
+ {static} List<T> sorted(Collection<T>,Comparator<T>)
+ {static} Collection<Long> ints2longs(Collection<Integer>)
+ {static} boolean allMatch(Collection<T>,Predicate<T>)
}
class com.gm.ultifi.service.access.someip.SomeIpClientManager {
}
class com.gm.ultifi.utils.SeatAreaIdConst {
+ {static} Integer GLOBAL_AREA_ID
}
class com.gm.ultifi.service.access.utils.TaskRunner {
- {static} String TAG
- {static} int CORE_THREADS
- {static} long KEEP_ALIVE_SECONDS
- {static} TaskRunner sTaskRunner
- ThreadPoolExecutor mExecutor
- Handler mHandler
+ {static} TaskRunner getInstance()
- ThreadPoolExecutor newThreadPoolExecutor()
+ void execute(Runnable)
+ void executeCallable(Callable<R>,OnCompletedCallback<R>)
+ ExecutorService getExecutor()
+ void shutdownService()
}
interface com.gm.ultifi.service.access.utils.TaskRunner$OnCompletedCallback {
~ void onComplete(R)
}
class com.gm.ultifi.service.access.utils.Utility {
- {static} String TAG
+ {static} List<String> buildTopicsList()
+ {static} boolean convertToBoolean(String)
+ {static} Boolean getBooleanValue(Signal)
+ {static} byte[] getBytes(Signal)
+ {static} Float getFloatValue(Signal)
+ {static} Integer getIntValue(Signal)
+ {static} K getKey(Map<K,V>,V)
+ {static} T getSignalValues(Signal)
+ {static} boolean between(int,int,int)
+ {static} boolean isInRange(double,double,double)
+ {static} boolean isInRange(float,float,float)
}


com.gm.ultifi.service.cabinclimate.utils.TaskRunner +.. com.gm.ultifi.service.cabinclimate.utils.TaskRunner$OnCompletedCallback
java.util.LinkedHashMap <|-- com.gm.ultifi.service.cabinclimate.utils.cache.LruMap
com.gm.ultifi.service.cabinclimate.response.config.PropertyConfig +.. com.gm.ultifi.service.cabinclimate.response.config.PropertyConfig$Builder
com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager +.. com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl
com.gm.ultifi.service.access.manager.propertymanager.CarPropertyEventCallback <|.. com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl
com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager +.. com.gm.ultifi.service.access.manager.propertymanager.CarPropertyExtensionManager$CarPropertyExtensionCallback
com.gm.ultifi.service.cabinclimate.manager.request.helper.BaseRequestProcessor <|-- com.gm.ultifi.service.cabinclimate.manager.request.helper.ZoneRequestProcessor
androidx.appcompat.app.AppCompatActivity <|-- com.gm.ultifi.service.MainActivity
com.gm.ultifi.service.access.manager.request.helper.BaseRequestProcessor <|-- com.gm.ultifi.service.access.manager.request.helper.SunroofRequestProcessor
java.util.LinkedHashMap <|-- com.gm.ultifi.service.access.utils.cache.LruMap
com.gm.ultifi.service.access.manager.ConnectionManager <|.. com.gm.ultifi.service.access.manager.UltifiLinkMonitor
androidx.lifecycle.LifecycleService <|-- com.gm.ultifi.service.AccessService
com.gm.ultifi.service.access.manager.ConnectionManager <|.. com.gm.ultifi.service.access.manager.CanManagerMonitor
com.gm.ultifi.service.access.manager.CanManagerMonitor +.. com.gm.ultifi.service.access.manager.CanManagerMonitor$OnCanManagerConnectionListener
com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager +.. com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl
com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyEventCallback <|.. com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager$CarPropertyEventListenerImpl
com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager +.. com.gm.ultifi.service.cabinclimate.manager.propertymanager.CarPropertyExtensionManager$CarPropertyExtensionCallback
com.gm.ultifi.service.access.manager.propertymanager.ProtobufMessageIds +.. com.gm.ultifi.service.access.manager.propertymanager.ProtobufMessageIds$SunroofFieldMask
com.gm.ultifi.service.cabinclimate.manager.request.helper.BaseRequestProcessor <|-- com.gm.ultifi.service.cabinclimate.manager.request.helper.SystemSettingsRequestProcessor
com.gm.ultifi.service.cabinclimate.utils.SignalMappingConstants +.. com.gm.ultifi.service.cabinclimate.utils.SignalMappingConstants$SystemSettings
com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory +.. com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory$RequestProcessorFactorySingleton
com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory +.. com.gm.ultifi.service.access.manager.request.rpc.RequestProcessorFactory$RequestProcessor
com.gm.ultifi.service.access.manager.request.listeners.RequestEventListener <|.. com.gm.ultifi.service.access.manager.request.listeners.UltifiLinkRequestEventListener
com.gm.ultifi.service.access.manager.request.helper.RequestProcessor <|.. com.gm.ultifi.service.access.manager.request.helper.BaseRequestProcessor
com.gm.ultifi.service.access.response.config.PropertyConfig +.. com.gm.ultifi.service.access.response.config.PropertyConfig$Builder
com.gm.ultifi.service.access.utils.SignalMappingConstants +.. com.gm.ultifi.service.access.utils.SignalMappingConstants$SystemSettings
com.gm.ultifi.service.access.manager.ConnectionManager <|.. com.gm.ultifi.service.access.manager.CarPropertyManagerMonitor
com.gm.ultifi.service.access.manager.CarPropertyManagerMonitor +.. com.gm.ultifi.service.access.manager.CarPropertyManagerMonitor$OnCarManagerConnectionListener
com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory +.. com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory$RequestProcessorFactorySingleton
com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory +.. com.gm.ultifi.service.cabinclimate.manager.request.rpc.RequestProcessorFactory$RequestProcessor
com.gm.ultifi.service.access.manager.request.helper.BaseRequestProcessor <|-- com.gm.ultifi.service.access.manager.request.helper.SomeIpRequestProcessor
com.gm.ultifi.service.cabinclimate.manager.ConnectionManager <|.. com.gm.ultifi.service.cabinclimate.manager.UltifiLinkMonitor
com.gm.ultifi.service.access.utils.cache.Cache <|.. com.gm.ultifi.service.access.utils.cache.LruCache
com.gm.ultifi.service.access.utils.cache.LruCache +.. com.gm.ultifi.service.access.utils.cache.LruCache$LruCacheSingleton
com.gm.ultifi.service.cabinclimate.utils.cache.Cache <|.. com.gm.ultifi.service.cabinclimate.utils.cache.LruCache
com.gm.ultifi.service.cabinclimate.utils.cache.LruCache +.. com.gm.ultifi.service.cabinclimate.utils.cache.LruCache$LruCacheSingleton
androidx.lifecycle.LifecycleService <|-- com.gm.ultifi.service.CabinClimateService
com.gm.ultifi.service.access.manager.request.listeners.RequestListener <|.. com.gm.ultifi.service.access.manager.request.listeners.UltifiLinkRequestListener
com.gm.ultifi.service.cabinclimate.response.mapper.BaseMapper <|.. com.gm.ultifi.service.cabinclimate.response.mapper.Zone
com.gm.ultifi.service.cabinclimate.manager.request.helper.RequestProcessor <|.. com.gm.ultifi.service.cabinclimate.manager.request.helper.BaseRequestProcessor
com.gm.ultifi.service.access.response.mapper.BaseMapper <|.. com.gm.ultifi.service.access.response.mapper.SunroofMapper
com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds +.. com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds$ZoneFieldMask
com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds +.. com.gm.ultifi.service.cabinclimate.manager.propertymanager.ProtobufMessageIds$SettingsFieldMask
android.content.BroadcastReceiver <|-- com.gm.ultifi.service.BootCompleteReceiver
com.gm.ultifi.service.cabinclimate.manager.ConnectionManager <|.. com.gm.ultifi.service.cabinclimate.manager.CarPropertyManagerMonitor
com.gm.ultifi.service.cabinclimate.manager.CarPropertyManagerMonitor +.. com.gm.ultifi.service.cabinclimate.manager.CarPropertyManagerMonitor$OnCarManagerConnectionListener
com.gm.ultifi.service.cabinclimate.manager.ConnectionManager <|.. com.gm.ultifi.service.cabinclimate.manager.CanManagerMonitor
com.gm.ultifi.service.cabinclimate.manager.CanManagerMonitor +.. com.gm.ultifi.service.cabinclimate.manager.CanManagerMonitor$OnCanManagerConnectionListener
com.gm.ultifi.service.cabinclimate.response.mapper.BaseMapper <|.. com.gm.ultifi.service.cabinclimate.response.mapper.SystemSettings
com.gm.ultifi.service.cabinclimate.manager.request.listeners.RequestListener <|.. com.gm.ultifi.service.cabinclimate.manager.request.listeners.UltifiLinkRequestListener
com.gm.ultifi.service.cabinclimate.manager.request.listeners.RequestEventListener <|.. com.gm.ultifi.service.cabinclimate.manager.request.listeners.UltifiLinkRequestEventListener
com.gm.ultifi.service.access.utils.TaskRunner +.. com.gm.ultifi.service.access.utils.TaskRunner$OnCompletedCallback
@enduml